name: Build and Release [Linux]
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Compilation
        run: ./gradlew build
      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: gradle-initializr.jar
          path: build/libs/*.jar